# Generated by Django 2.2.4 on 2019-08-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='instituicao',
            new_name='curso',
        ),
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Instituicao'),
        ),
        migrations.AlterField(
            model_name='disc_has_aluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Aluno'),
        ),
        migrations.AlterField(
            model_name='disc_has_aluno',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Disciplina'),
        ),
    ]
