# Generated by Django 2.2.4 on 2019-09-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='data',
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(max_length=20)),
                ('peso', models.PositiveIntegerField(default=1)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Prova'), (2, 'Trabalho')])),
                ('data', models.DateField()),
                ('dataPublicacao', models.DateField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Turma')),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='avaliacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Avaliacao'),
            preserve_default=False,
        ),
    ]
