# Generated by Django 2.2.4 on 2019-09-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.PositiveIntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.PositiveIntegerField(blank=True, default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.PositiveIntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='rg',
            field=models.PositiveIntegerField(blank=True, default=None, unique=True),
        ),
    ]
