# Generated by Django 2.2.4 on 2019-09-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0002_auto_20190911_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.PositiveIntegerField(blank=True, default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.PositiveIntegerField(blank=True, default=None, unique=True),
        ),
    ]
