# Generated by Django 2.2.4 on 2019-09-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0002_auto_20190917_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
