# Generated by Django 2.2.4 on 2019-08-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0003_auto_20190822_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaspapp.Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaspapp.Instituicao'),
        ),
        migrations.AlterField(
            model_name='disc_has_aluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaspapp.Aluno'),
        ),
        migrations.AlterField(
            model_name='disc_has_aluno',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaspapp.Disciplina'),
        ),
    ]
