# Generated by Django 2.2.4 on 2019-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0003_auto_20190911_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.PositiveIntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.PositiveIntegerField(default=None, unique=True),
        ),
    ]
