# Generated by Django 2.2.4 on 2019-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0003_auto_20190918_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(null=True),
        ),
    ]
