# Generated by Django 2.2.4 on 2019-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0004_auto_20190822_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cargaHoraria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='cargaHoraria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='serie',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='documento',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
