# Generated by Django 2.2.4 on 2019-09-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0004_auto_20190918_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
