# Generated by Django 2.2.4 on 2019-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0004_auto_20190911_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='rg',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
