# Generated by Django 2.2.4 on 2019-08-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0005_auto_20190823_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='documento',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cargaHoraria',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='cargaHoraria',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='serie',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
