# Generated by Django 2.2.4 on 2019-12-16 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0006_auto_20190918_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='matricula',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='alunos', through='vaspapp.Matricula', to='vaspapp.Disciplina'),
        ),
    ]
