# Generated by Django 2.2.4 on 2019-08-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0006_auto_20190825_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(related_name='alunos', to='vaspapp.Disciplina'),
        ),
        migrations.DeleteModel(
            name='Disc_has_aluno',
        ),
    ]
