# Generated by Django 2.2.4 on 2019-11-06 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0006_auto_20190918_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
