# Generated by Django 2.2.4 on 2019-08-26 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0007_auto_20190825_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaspapp.Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='vaspapp.Disciplina'),
        ),
    ]
