# Generated by Django 2.2.4 on 2019-09-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0008_auto_20190826_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc_has_aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='documento',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('rg', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True)),
                ('cpf', models.PositiveIntegerField(blank=True, default=None, null=True, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaspapp.Curso')),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='professores', to='vaspapp.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('dha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Disc_has_aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presenca', models.BinaryField()),
                ('dha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Disc_has_aluno')),
            ],
        ),
        migrations.AddField(
            model_name='disc_has_aluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Aluno'),
        ),
        migrations.AddField(
            model_name='disc_has_aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Curso'),
        ),
    ]
