# Generated by Django 2.2.4 on 2019-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0009_auto_20190910_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
