# Generated by Django 2.2.4 on 2019-09-10 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0010_auto_20190910_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disc_has_aluno',
            new_name='Matricula',
        ),
        migrations.RenameField(
            model_name='frequencia',
            old_name='dha',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='dha',
            new_name='matricula',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.AddField(
            model_name='matricula',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vaspapp.Disciplina'),
            preserve_default=False,
        ),
    ]
