# Generated by Django 2.2.4 on 2019-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaspapp', '0011_auto_20190910_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='alunos', through='vaspapp.Matricula', to='vaspapp.Disciplina'),
        ),
    ]
